#!/usr/bin/env bash

for y in 2019 2018 2017 2016 2015 2014 2013 2012 2011 2010 2009; do
  echo "Year $y";
  for x in Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec; do
    echo "Setting Month to $x";
    passalong=$x-$y
    tst $passalong
  done
  echo "Completed year $y..."
done
  
